### ISSUE TITLE
typeahead metadata

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#1]
See the bottom of the below image. We want typeahead for speakers, categories and tags. We can load a list in a JSON or YAML file. We should have some friction to creating something that isn't in our list, maybe with a confirm popup.

![image](https://user-images.githubusercontent.com/755825/229138663-7d1a5a20-0850-4810-97ef-ee83a8c50a88.png)

**Comment by kanzure** [comment]
what is typeahead?

**Comment by Emmanuel-Develops** [comment]
> what is typeahead?

suggestions while typing. Like a dropdown on an input providing available options that closely match what the user types

**Comment by Emmanuel-Develops** [comment]
For now speakers, categories and tags
