### ISSUE TITLE
when metadata is updated on the editor page, it doesn't show up on the index page

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#10]
Update the category on the editor page

<img width="224" alt="Screen Shot 2023-04-13 at 5 28 56 PM" src="https://user-images.githubusercontent.com/755825/231887061-b20d7cad-8f0f-4493-9850-b64ad2051ddb.png">

No change on the index page
<img width="822" alt="Screen Shot 2023-04-13 at 5 29 09 PM" src="https://user-images.githubusercontent.com/755825/231887060-0e57e18c-6b32-4003-8ac2-6a9417387a1e.png">

**Comment by Emmanuel-Develops** [comment]
#18 closes this issue
