### ISSUE TITLE
confirmation modal

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#101]
after clicking on the submission button from the edit page these should pop up:

![image](https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/600751c1-e07f-4118-a163-a6592f3e104f)

**Comment by adamjonas** [comment]
This has one too many modals. We should cut the modal below now that we have the other one. We should put (where it is shipping on the previous modal below the bullet points and above the buttons.

<img width="465" alt="Screenshot 2023-07-03 at 9 27 20 AM" src="https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/72c1dd75-291d-4e01-b630-96713315e41b">

**Comment by Extheoisah** [comment]
Closing this now
