### ISSUE TITLE
Surface ability to modify btctranscript dir location as metadata from edit page

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#105]
Should be hard to modify but it will be a pain if editor can't do it at all

**Comment by Extheoisah** [comment]
This needs more clarity.

**Comment by adamjonas** [comment]
Updated title to clarify

**Comment by adamjonas** [comment]
`loc` is metadata that determines which directory this transcript will end up in in the repo https://github.com/bitcointranscripts/bitcointranscripts. This is not currently accessible on the edit page but it should be. The vast majority of time it won't need updating so we want people to mostly use the default, but should allow for the case where people want to select existing directories and in some cases (with friction like adding new authors), we can allow reviewers to create their own directories.

**Comment by Extheoisah** [comment]
closed by https://github.com/bitcointranscripts/transcription-review-front-end/pull/145
