### ISSUE TITLE
Alby Integration frontend

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/transcription-review-front-end#148]

**Comment by kouloumos** [comment]
@Emmanuel-Develops or @Extheoisah can you give an update on the status of this?

**Comment by Extheoisah** [comment]
This is supposed to be an additional payment method for reviewers. But we haven't had the bandwidth to prioritize it because it requires some work on the backend as well especially given that we already have ln address withdraw and invoice withdraw

**Comment by kouloumos** [comment]
It sounds that we might never get to this. I'm going to close the issue and we can reopen it if we ever prioritize integration with Alby.
