### ISSUE TITLE
change site metadata 

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#19]
favicon, description, etc

**Comment by adamjonas** [comment]
mostly closed by #18, still need to update the favicon

**Comment by Emmanuel-Develops** [comment]
Isn't this the icon?
<img width="369" alt="Screenshot 2023-04-24 at 8 42 25 PM" src="https://user-images.githubusercontent.com/62019510/234099349-2f4f7cca-5a04-4058-8f8a-384b8c28e64c.png">

**Comment by adamjonas** [comment]
That's not an appropriate Ivón

**Comment by adamjonas** [comment]
closed by #31
