### ISSUE TITLE
front matter validation

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#191]
This was recently submitted - this front matter is invalid and should be validated before a PR is opened.

```
---
title: Lightning Dev Kit: Making Lightning More Accessible to Developers - Matt Corallo - TABConf 2021
transcript_by: ttiiggss via review.btctranscripts.com
media: https://www.youtube.com/watch?v=W-ajI5YleIo
tags: ["Lightning","C-Lightning","Lnd","Wallet","Layer 2"]
speakers: ["Matt Corallo"]
categories: ["conference"]
date: 2021-11-05
---

## Lightning Dev Kit: Making Lightning More Accessible to Developers ##

**Speaker**: Matt Corallo

**Date**: November 5th, 2021

**Transcript By**: tigs

**Tags**: Lightning, C-Lightning, LND, Wallet, Layer 2

**Category**: Conference

**Media**: https://www.youtube.com/watch?v=W-ajI5YleIo

---

```

**Comment by Extheoisah** [comment]
Can you give more clarity on this issue? Its not entirely clear to me what validation we have to do here

**Comment by adamjonas** [comment]
The title has a colon in it is what makes it invalid but lower case tags and categories would be preferable

**Comment by Extheoisah** [comment]
related -> https://github.com/bitcointranscripts/transcription-review-front-end/issues/192

**Comment by Extheoisah** [comment]
This issue can be closed now because the new github implementation fixes this. We now accept transcript titles in quotes ("...")
