### ISSUE TITLE
Preview transcript before claiming

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/transcription-review-front-end#195]
Is there a reason that the potential reviewer cannot see the transcript before claiming? I think that if they know what they're getting into might increase the chance of finishing the job.

As it stands, for the user to experience something interesting after that first login, they have to click "Claim", and that "locks" the transcript for the next 24h, probably degrading the user experience of the subsequent users, especially if there are not unlimited transcripts available.

A different (or additional) approach could be the option for the user to "Cancel" their claim, instead of waiting for 24h. Of course, if my above assumption is correct and users actually care of the content that they are transcribing, this will result to a chain of claims and cancellations in the pursue of the "correct" transcript.

For the preview, the user could see the same Editor screen but in preview-only mode and with the rest of the input boxes disabled.

**Comment by Extheoisah** [comment]
IMO, The preview option is better UX than "claiming then cancel". What are your thoughts on this?
@Emmanuel-Develops @adamjonas

**Comment by Emmanuel-Develops** [comment]
Preview is good  👍

**Comment by kouloumos** [comment]
AI generated transcripts are now committed on https://github.com/bitcointranscripts/bitcointranscripts in order to be queued for review, therefore they are available at https://btctranscripts.com/. After #250 we provide a link to the transcript that users can access before claiming.
