### ISSUE TITLE
Shared state between expired reviews and transcripts waiting for review

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/transcription-review-front-end#197]
When a review has expired, although the user cannot access it from the "My Account" page, they can still access it from its url, e.g `reviews/26`. In the url the review is shown as "expired" but all the functionality is available. The user can make changes and submit them to the backend successfully.

It seems that there is only source of truth for each review, so if I open an expired review and makes changes, those modify the original review which is now available for someone else to claim. 
![expired_review](https://github.com/bitcointranscripts/transcription-review-front-end/assets/18506343/53d728df-1250-4212-bea7-1ef95cf7d2bd)

Another issue with this behavior is that it allows the possibility for two users to simultaneously edit a review. Alice has access to an expired review and Bob just claimed the same transcript for review. The current state of the edited transcript is shown in both review pages and both  are allowed to modify it. 
![expired_review2](https://github.com/bitcointranscripts/transcription-review-front-end/assets/18506343/e120f1fa-b192-463a-b0b4-5345ee412855)

**Comment by Emmanuel-Develops** [comment]
Mm, that's odd. User shouldn't be able to access expired reviews
I added this fix about 2 weeks ago
here: https://github.com/bitcointranscripts/transcription-review-front-end/pull/193

**Comment by kouloumos** [comment]
This is no longer an issue.
