### ISSUE TITLE
GitHub forks and sync with master branch of bitcointranscripts

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/transcription-review-front-end#225]
It seems to me that there is an "issue" with the way that we are handling a reviewers fork.

**Example in the wild**
If you see this review submission: https://github.com/bitcointranscripts/bitcointranscripts/pull/317, the user wants to merge a transcript at `bitcoin-magazine/bitcoin-explained`. But because their fork is not sync with master (they forked on a previous time because this is not their first review), they do not have the latest view of the master branch, therefore they also try to push the file `bitcoin-magazine/bitcoin-explained/_index.md`, which is already in master.

Is there a way to first sync with master, and then fork the new branch?
We already have people reviewing more than one transcripts, and although the recreation of the `_index.md` file is the only issue that we have, we might have to deal with unexpected issues in the future if not everybody are synced to the latest HEAD.

**Comment by Extheoisah** [comment]
closing this as it has been fixed here https://github.com/bitcointranscripts/transcription-review-front-end/blob/db39e03efac9077879be872ec2eb85f3c89efaae/src/pages/api/github/pr.ts#L45 
function definition here -> https://github.com/bitcointranscripts/transcription-review-front-end/blob/db39e03efac9077879be872ec2eb85f3c89efaae/src/utils/github.ts#L154
