### ISSUE TITLE
Empty commit added with every new review submission

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/transcription-review-front-end#240]
I encountered an issue after claiming a transcript on staging. [Upon submission](https://github.com/jacoby71/bitcointranscripts/pull/1), I noticed an additional [empty commit](https://github.com/jacoby71/bitcointranscripts/pull/1/commits/73aa2717aec6f008ece6984710d6524e223584f5) in the GitHub PR. While the submission was active, I made edits to the transcript on the website and re-submitted, resulting in [another unexpected empty commit](https://github.com/jacoby71/bitcointranscripts/pull/1/commits/86294aab6ed79e4152bb7ac31b5d13fc024ddfcc) being added.

**Comment by Extheoisah** [comment]
should fix https://github.com/bitcointranscripts/transcription-review-front-end/issues/241
