### ISSUE TITLE
Remove the `/tutorial` page

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/transcription-review-front-end#273]
The tutorial page has become outdated and largely replicates content already available on the homepage.

Actions to be taken:
- Eliminate the tutorial page from the website.
- Remove the link to the tutorial page from the navigation bar.
- Introduce anchors/sections on the homepage specifically for the "Here’s everything you need to start" section, for each step (1, 2, 3), as well as the tips section. This will make it easier to redirect users on those section if we decide to do so.

**Comment by Extheoisah** [comment]
@adamjonas had the same thoughts a while back after the homepage redesign. I agree with this lin of thought and it should be a fairly easy task to complete
