### ISSUE TITLE
Don't allow user to claim for additional transcript if a user has an active review

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#52]
Disabling the button is preferred to this error:

<img width="450" alt="Screen Shot 2023-05-11 at 9 14 09 PM" src="https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/b01260dc-db92-47da-a621-06a52644889f">

**Comment by Emmanuel-Develops** [comment]
@nassersaazi we have a bit of differing logic for active reviews. I only realized it after working on this issue.

The backend currently uses `transcripts.claimedBy` for active reviews to prevent a claim action, but this is limited to transcripts and doesn't account for expired reviews.

On the other end I'm checking for claimedAt time + 24hrs and `mergedAt` field.

**Comment by adamjonas** [comment]
@Emmanuel-Develops coild you take a shot at updating the function to be what you'd prefer ?

**Comment by Emmanuel-Develops** [comment]
> @Emmanuel-Develops coild you take a shot at updating the function to be what you'd prefer ?

Sure, although I’d have to ping @nassersaazi so we aren’t out of sync

**Comment by adamjonas** [comment]
closed via [#33](https://github.com/bitcointranscripts/transcription-review-backend/pull/33)
