### ISSUE TITLE
Same branch on re-submitted transcripts

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/transcription-review-front-end#55]
If a transcript has been submitted earlier, then resubmitted after some changes, the same branch used to make the PR initially on create PR logic should be re-used. This keeps the further iterations of that transcript on the same PR.

**Comment by adamjonas** [comment]
Agree though I think this is a v2. I'm imagining that things are submitted once in most cases.

**Comment by Emmanuel-Develops** [comment]
Alright then, I’m halfway done but running into some bugs. I will shelf that for V2

**Comment by Emmanuel-Develops** [comment]
This was for a legacy flow.
Users currently can't edit the transcript after submission, except they manually visit the URL that contains that review.
i think the question here is wether we add friction, prevent them doing that completely or allow them.
my thoughts are:
- User goes to the review link of a pending review (submitted and not merged) we prevent them from seeing that page (e.g review is pending splash screen)
- User goes to the review link of a pending review, they can see the review editing page but with disabled save and submit buttons.
- User goes to the review link of a pending review, the editing page is no different from an active review (what we have now), but the next API route throws an error if saving or submitting a pending review
- User goes to the review link of a pending review, and if user submits review it resubmits to the same branch thereby updating PR

cc: @adamjonas @Extheoisah

**Comment by adamjonas** [comment]
> User goes to the review link of a pending review, and if user submits review it resubmits to the same branch thereby updating PR

This

**Comment by 0tuedon** [comment]
> * User goes to the review link of a pending review, and if user submits review it resubmits to the same branch thereby updating PR
> 
> cc: @adamjonas @Extheoisah
> 

Hey @Emmanuel-Develops, are we sticking with them typing the url by manual for them to resubmit a PR, or we are given them an ablity to click on the review and visit the review link cc @adamjonas  @Extheoisah

**Comment by Emmanuel-Develops** [comment]
> > * User goes to the review link of a pending review, and if user submits review it resubmits to the same branch thereby updating PR
> > 
> > cc: @adamjonas @Extheoisah
> 
> Hey @Emmanuel-Develops, are we sticking with them typing the url by manual for them to resubmit a PR, or we are given them an ablity to click on the review and visit the review link cc @adamjonas @Extheoisah

Ideally, we would want a flow where they can update a review after submitting (most likely `Update Review` button on a submitted review in the current reviews table)
But now, getting the feature working with the current friction (i.e they manually enter the link) is good enough. We can worry on how the UX works when the feature is ready

**Comment by adamjonas** [comment]
@0tuedon what is the expected method to revisit a review the first submission?

<img width="1300" alt="Screenshot 2023-10-18 at 4 23 52 PM" src="https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/00e3360c-1dde-4ba9-b74a-c6dc911fa9ce">

The under review button points to the PR.

**Comment by adamjonas** [comment]
also https://github.com/bitcointranscripts/transcription-review-front-end/pull/189/files#r1364498658

**Comment by 0tuedon** [comment]
> also https://github.com/bitcointranscripts/transcription-review-front-end/pull/189/files#r1364498658

ACK, would be working on both.
