### ISSUE TITLE
on the profile page reviews should either be active or past, not both

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#58]
Review of a transcript should be in either category, but not both:

<img width="1309" alt="Screen Shot 2023-05-15 at 10 27 09 AM" src="https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/7ad05580-75c1-497a-9816-dd0befa7551a">

**Comment by Emmanuel-Develops** [comment]
There is an edge case where this might happen. If a user claims a transcript, and the review expires then the transcript is requeued. As the review isn't active anymore it shows up as a past job (maybe we have a column on past jobs table that shows wether it was merged or expired).
If the user claims that requeued transcript again it will show up on the current Job.

I believe this was the case here.

**Comment by adamjonas** [comment]
Achievement unlocked

<img width="1295" alt="Screenshot 2023-06-05 at 2 39 57 PM" src="https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/375b2989-4641-4783-a168-7d85291b5e21">
