### ISSUE TITLE
empty tables need better placeholders

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#72]
A simple no current jobs would suffice here or better yet, don't show the table at all.

<img width="1306" alt="Screen Shot 2023-05-23 at 4 12 54 PM" src="https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/7880380b-3a99-464e-93c2-9143c4315a1c">

**Comment by Extheoisah** [comment]
@BalogunofAfrica You self-assigned this. How's it going? Any updates?
