### ISSUE TITLE
as an admin, I can grant admin permissions to reviewers

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#77]
Easy first step would be to put a button on a profile page that admins can access

**Comment by Extheoisah** [comment]
We need the UI for this issue. The backend has the functionality already.

**Comment by adamjonas** [comment]
> Easy first step would be to put a button on a profile page that admins can access

I'd suggest this for whoever picks it up

**Comment by kouloumos** [comment]
Closed with https://github.com/bitcointranscripts/transcription-review-front-end/pull/294
