### ISSUE TITLE
Add search and pagination to index queue

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#78]
As a potential reviewer, I'd like to see all the transcripts that interest me.

We have yet to see that page with a lot of transcripts. But that's about to change...

**Comment by adamjonas** [comment]
Pagination is the higher priority.

**Comment by Extheoisah** [comment]
We have pagination now.

**Comment by adamjonas** [comment]
I don't think we need search until we have a lot of transcripts loaded. @kouloumos hace an opinion here?

**Comment by kouloumos** [comment]
> I don't think we need search until we have a lot of transcripts loaded. @kouloumos hace an opinion here?

I agree. I believe that even with **a lot of transcripts**, filtering by {category, tag, speaker, ...} will be more useful than search as a first step.

**Comment by Extheoisah** [comment]
So I can close this issue?
