### ISSUE TITLE
add status to past reviews

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#81]
As a reviewer, I should be able to look at the PRs that I have submitted and see what the status of old reviews are.

**Comment by Emmanuel-Develops** [comment]
cdlk

**Comment by adamjonas** [comment]
Link to PR and btctranscripts for merged PRs

![image](https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/a12619d7-4d0c-4699-a507-ee9cc2f53c95)
